### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by IntinteDAO** [Levyaton/WindbotTemplateGenerator#1]
Hello. I don't know about Java, and I may find your project useful (if I understand what it does, it has basic rules for cards and creates these rules for WindBot based on the database).

But how to build / run a project? I tried using the console (mvn build / mvn compile) and failed.

**Comment by Levyaton** [comment]
Hey, glad you may find a use for it! I personally use intellij, and I updated the project to include the intellij configuration files, so that using it shouldn't be an issue. You can run it using any other ide or method, I think, just be sure that the files aren't missing any necessary imports if you do. If you aren't that experienced with java, I really just recommend getting Intellij Community Edition, it's free and, as I mentioned, the project should work in it. If you have any other questions, be it proper project configuration, or how this application works, please, ask, I will be happy to help. 

Also, the idea of the app is that when you wish to write a custom windbot AI for a deck, you must manually add a bunch of code that is always basically the same (you have to set up each card and the methods related to them). It isn't a particularly difficult process, but it is really mind numbing. This program aims to make the process a whole lot easier, as you just provide the deck file and the program generates an appropriate template, saving you probably hours, or, at least, many minutes. I think the template should work for a basic ai, without the need for further modification, though I haven't tried it myself. You can, however, modify the generator files, so that it adds the potentially missing code. If you try it and find out that the basic ai doesn't work, and figure out what code is missing, please, let me know, and I will add it.

Hope this helps!

**Comment by IntinteDAO** [comment]
Overall, what I want to do is to free implementatation of the game.

After Konami took off a lot of unofficial clones (they had such a right technically) I decided that maybe it is worth to make a game inspired by Yu-Gi-Oh, or more precisely by classical scenes. But I think that AI and a server, which would pair people, will be useful for this.

I'm not an expert on C# and Java, so I don't know how to bite it, but your piece of code, as I understand it, allows you to create a very basic version of AI scripts.

I think the code is building up, but I don't know how to run it (because I thought I would get some C# code for Windbot or similar).

**Comment by sspony** [comment]
I'm also confused about the building, I wasn't able to run the main method on RunMe.java. If you could help with the configuration that would be great! This is what I keep getting (sorry for being a noob T_T):
Error: Could not find or load main class RunMe
Caused by: java.lang.ClassNotFoundException: RunMe

**Comment by Levyaton** [comment]
Currently, the easiest way to run it is by following these steps:

1. [Install JDK 13](https://www.oracle.com/java/technologies/javase-jdk13-downloads.html)
2. Install Intellij Community Edition
3. Open Intellij and click on File->New->Project From Version Controll
4. Add https://github.com/Levyaton/WindbotTemplateGenerator.git as the url and make the directory the location you want the repository to be created in
5. Run main (if you want the templetes to be created, you must first have the deckfiles (the files containing the card id's, ending with a .ydk suffix) in the UserFiles/decks folder of the project)

That should do it, nothing else should be required. Please, let me know if the problem was resolved, or if you still couldn't get it to work. Best of luck!

**Comment by Levyaton** [comment]
> Overall, what I want to do is to free implementatation of the game.
> 
> After Konami took off a lot of unofficial clones (they had such a right technically) I decided that maybe it is worth to make a game inspired by Yu-Gi-Oh, or more precisely by classical editions. But I think that AI and a server, which would pair people, will be useful for this.
> 
> I'm not an expert on C# and Java, so I don't know how to bite it, but your piece of code, as I understand it, allows you to create a very basic version of AI scripts.
> 
> I think the code is building up, but I don't know how to run it (because I thought I would get some C# code for Windbot or similar).

Do you have the .ydk files in the UserFiles folder, and do you have JDK 13 installed? Also, please tell me if you are getting an error, it will make helping you a lot easier. Sorry for the late replay, school was hell recently, lol

**Comment by sspony** [comment]
> Currently, the easiest way to run it is by following these steps:
> 
> 1. [Install JDK 13](https://www.oracle.com/java/technologies/javase-jdk13-downloads.html)
> 2. Install Intellij Community Edition
> 3. Open Intellij and click on File->New->Project From Version Controll
> 4. Add https://github.com/Levyaton/WindbotTemplateGenerator.git as the url and make the directory the location you want the repository to be created in
> 5. Run main (if you want the templetes to be created, you must first have the deckfiles (the files containing the card id's, ending with a .ydk suffix) in the UserFiles/decks folder of the project)
> 
> That should do it, nothing else should be required. Please, let me know if the problem was resolved, or if you still couldn't get it to work. Best of luck!

Those steps worked. Thank you!

**Comment by IntinteDAO** [comment]
> Run main (if you want the templetes to be created, you must first have the deckfiles (the files containing the card id's, ending with a .ydk suffix) in the UserFiles/decks folder of the project)

Sorry, I don't exactly know how to execute it. I build (compile) a project, copy the deck (and my own cards.cdb) to the project directory and run nothing happens via alt + shift + f10 and I don't get nothing. No bugs, but also no files in results

**Comment by Levyaton** [comment]
> > Run main (if you want the templetes to be created, you must first have the deckfiles (the files containing the card id's, ending with a .ydk suffix) in the UserFiles/decks folder of the project)
> 
> Sorry, I don't exactly know how to execute it. I build (compile) a project, copy the deck (and my own cards.cdb) to the project directory and run nothing happens via alt + shift + f10 and I don't get nothing. No bugs, but also no files in results

Hey, did you put the cards.cdb file in the WindbotTemplateGenerator/Game/AI/Decks/TempleteGenerator/UserFiles/ folder, and your own deck file in the WindbotTemplateGenerator/Game/AI/Decks/TempleteGenerator/UserFiles/decks/ folder?

**Comment by IntinteDAO** [comment]
@Levyaton Yep (except WindbotTemplateGenerator)
![20210207_22h36m43s_grim](https://user-images.githubusercontent.com/56807194/107160211-29f68f00-6995-11eb-9fba-673eccfdb8a8.png)

**Comment by SamuelB-YGO** [comment]
@Levyaton what format are you supposed to compile under?

**Comment by SamuelB-YGO** [comment]
> @Levyaton what format are you supposed to compile under?

Nevermind.
